create table if not exists public.caller_security_state (
  tenant_id text not null,
  caller_key text not null,
  risk_score integer not null default 0,
  security_strikes integer not null default 0,
  rate_limit_blocks integer not null default 0,
  blocked_until timestamptz,
  permanent_block boolean not null default false,
  last_reason text,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, caller_key)
);

create table if not exists public.caller_security_events (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  caller_key text not null,
  event_type text not null,
  severity text not null default 'INFO',
  risk_delta integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists caller_security_events_lookup_idx on public.caller_security_events (tenant_id, caller_key, created_at desc);
create index if not exists caller_security_events_type_idx on public.caller_security_events (tenant_id, caller_key, event_type, created_at desc);

create or replace function public.evaluate_inbound_call_security(p_tenant_id text,p_caller_key text)
returns table(decision text,blocked_until timestamptz,permanent_block boolean,calls_1m integer,calls_5m integer,calls_1h integer,risk_score integer,security_strikes integer,rate_limit_blocks integer,reason text)
language plpgsql security definer set search_path=public as $$
declare s public.caller_security_state%rowtype; c1 integer; c5 integer; c60 integer; abusive boolean; new_block_until timestamptz; block_reason text;
begin
  if p_tenant_id is null or btrim(p_tenant_id)='' then raise exception 'tenant_id_required'; end if;
  if p_caller_key is null or btrim(p_caller_key)='' then raise exception 'caller_key_required'; end if;
  insert into public.caller_security_state(tenant_id,caller_key,last_seen_at) values(p_tenant_id,p_caller_key,now())
    on conflict(tenant_id,caller_key) do update set last_seen_at=excluded.last_seen_at,updated_at=now();
  select cs.* into s from public.caller_security_state cs where cs.tenant_id=p_tenant_id and cs.caller_key=p_caller_key for update;
  insert into public.caller_security_events(tenant_id,caller_key,event_type,severity) values(p_tenant_id,p_caller_key,'CALL_ATTEMPT','INFO');
  select count(*)::integer into c1 from public.caller_security_events e where e.tenant_id=p_tenant_id and e.caller_key=p_caller_key and e.event_type='CALL_ATTEMPT' and e.created_at>=now()-interval '1 minute';
  select count(*)::integer into c5 from public.caller_security_events e where e.tenant_id=p_tenant_id and e.caller_key=p_caller_key and e.event_type='CALL_ATTEMPT' and e.created_at>=now()-interval '5 minutes';
  select count(*)::integer into c60 from public.caller_security_events e where e.tenant_id=p_tenant_id and e.caller_key=p_caller_key and e.event_type='CALL_ATTEMPT' and e.created_at>=now()-interval '1 hour';
  if s.permanent_block then return query select 'BLOCK'::text,s.blocked_until,true,c1,c5,c60,s.risk_score,s.security_strikes,s.rate_limit_blocks,'PERMANENT_BLOCK'::text; return; end if;
  if s.blocked_until is not null and s.blocked_until>now() then return query select 'BLOCK'::text,s.blocked_until,false,c1,c5,c60,s.risk_score,s.security_strikes,s.rate_limit_blocks,'ACTIVE_TEMP_BLOCK'::text; return; end if;
  abusive := c1>=5 or c5>=8 or c60>=20;
  if abusive then
    block_reason := case when c1>=5 then 'CALL_RATE_1M' when c5>=8 then 'CALL_RATE_5M' else 'CALL_RATE_1H' end;
    new_block_until := case when s.rate_limit_blocks=0 then now()+interval '1 hour' when s.rate_limit_blocks=1 then now()+interval '24 hours' else now()+interval '7 days' end;
    update public.caller_security_state as cs set rate_limit_blocks=cs.rate_limit_blocks+1,risk_score=least(100,cs.risk_score+3),blocked_until=new_block_until,last_reason=block_reason,updated_at=now()
      where cs.tenant_id=p_tenant_id and cs.caller_key=p_caller_key returning cs.* into s;
    insert into public.caller_security_events(tenant_id,caller_key,event_type,severity,risk_delta,metadata)
      values(p_tenant_id,p_caller_key,'RATE_LIMIT_BLOCK','HIGH',3,jsonb_build_object('reason',block_reason,'calls_1m',c1,'calls_5m',c5,'calls_1h',c60,'blocked_until',new_block_until));
    return query select 'BLOCK'::text,new_block_until,false,c1,c5,c60,s.risk_score,s.security_strikes,s.rate_limit_blocks,block_reason; return;
  end if;
  return query select 'ALLOW'::text,null::timestamptz,false,c1,c5,c60,s.risk_score,s.security_strikes,s.rate_limit_blocks,'OK'::text;
end $$;

create or replace function public.record_caller_security_signal(p_tenant_id text,p_caller_key text,p_event_type text,p_severity text,p_risk_delta integer,p_metadata jsonb default '{}'::jsonb,p_high_confidence boolean default false)
returns table(action text,blocked_until timestamptz,permanent_block boolean,risk_score integer,security_strikes integer,reason text)
language plpgsql security definer set search_path=public as $$
declare s public.caller_security_state%rowtype; strikes_24h integer; should_permanent boolean:=false; new_block_until timestamptz;
begin
  insert into public.caller_security_state(tenant_id,caller_key,last_seen_at) values(p_tenant_id,p_caller_key,now()) on conflict(tenant_id,caller_key) do nothing;
  select cs.* into s from public.caller_security_state cs where cs.tenant_id=p_tenant_id and cs.caller_key=p_caller_key for update;
  insert into public.caller_security_events(tenant_id,caller_key,event_type,severity,risk_delta,metadata) values(p_tenant_id,p_caller_key,p_event_type,coalesce(p_severity,'INFO'),greatest(0,p_risk_delta),coalesce(p_metadata,'{}'::jsonb));
  update public.caller_security_state as cs set risk_score=least(100,cs.risk_score+greatest(0,p_risk_delta)),security_strikes=cs.security_strikes+case when p_high_confidence then 1 else 0 end,last_reason=p_event_type,last_seen_at=now(),updated_at=now()
    where cs.tenant_id=p_tenant_id and cs.caller_key=p_caller_key returning cs.* into s;
  select count(*)::integer into strikes_24h from public.caller_security_events e where e.tenant_id=p_tenant_id and e.caller_key=p_caller_key and e.severity in('HIGH','CRITICAL') and e.created_at>=now()-interval '24 hours';
  if p_high_confidence and strikes_24h>=2 then
    new_block_until := case when s.security_strikes<=2 then now()+interval '1 hour' when s.security_strikes<=4 then now()+interval '24 hours' else now()+interval '7 days' end;
    update public.caller_security_state as cs set blocked_until=greatest(coalesce(cs.blocked_until,'epoch'::timestamptz),new_block_until),updated_at=now() where cs.tenant_id=p_tenant_id and cs.caller_key=p_caller_key returning cs.* into s;
  end if;
  should_permanent := s.security_strikes>=8 and s.rate_limit_blocks>=3 and s.risk_score>=25;
  if should_permanent then
    update public.caller_security_state as cs set permanent_block=true,blocked_until=null,last_reason='PERSISTENT_HOSTILE_BEHAVIOR',updated_at=now() where cs.tenant_id=p_tenant_id and cs.caller_key=p_caller_key returning cs.* into s;
  end if;
  return query select case when s.permanent_block or (s.blocked_until is not null and s.blocked_until>now()) then 'BLOCK_FUTURE_CALLS' else 'ALLOW_FUTURE_CALLS' end,s.blocked_until,s.permanent_block,s.risk_score,s.security_strikes,case when s.permanent_block then 'PERSISTENT_HOSTILE_BEHAVIOR' else p_event_type end;
end $$;
